<a href="https://colab.research.google.com/github/Bahrombekk/numpy/blob/main/_numpy_homework_ipynb.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Create array

# Numerical Python

In [ ]:
import numpy as np

In [ ]:
def list_arr(list1):
  '''
  Convert list the array
  '''
  return np.array(list1)
list1=[1,2,3,4,5]
list_arr(list1)

array([1, 2, 3, 4, 5])

In [ ]:
def even_array(lst):
  '''
  Convert only even items to array
  '''
  l1=[]
  for i in lst:
    if i%2==0:
      l1.append(i)
  return np.array(l1)
even_array([1,2,3,4,5,6,7])

array([2, 4, 6])

## Numpy array properties


In [ ]:
def arry_1D():
  '''
  Create any 1D array 
  '''
  lst = [1,2,3,4,5]
  # CODE
  return np.array(lst)
arry_1D()
  

array([1, 2, 3, 4, 5])

In [ ]:
def arry_2D():
  '''
  Create any 2D array 
  '''
  lst =[[1,2,3,4],[5,6,7,8]]
  # CODE
  return np.array(lst)
arry_2D()

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [ ]:
def arry_3D():
  '''
  Create any 3D array 
  '''
  lst = [[1,2,3,4],[5,6,7,8],[4,8,9,6]]
  # CODE
  return np.array(lst)
arry_3D()

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [4, 8, 9, 6]])

### The shape of the array
 **shape**  - Return the shape of an array.					
 **Returns**: tuple of ints



In [ ]:
def arry_3x3():
  '''
  Create any 3x3 array 
  '''
  lst = [[1,2,3],
         [4,5,6],
         [7,8,9]]
  # CODE
  return np.array(lst)
arry_3x3()

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
def arry_2x3(lst):
  '''
  Create lst to 2x3 array 
  return 1D
  '''
  # CODE
  return np.array(lst)
lst =[[2,3,4],
         [5,6,7]]
arry_2x3(lst)

array([[2, 3, 4],
       [5, 6, 7]])

## The dtype of the array


### np.int8

In [ ]:
def array_dtype_int8(lst):
  '''
  Create an array dtype int8
  return nD array
  '''
  l=np.array(lst,dtype=np.int8)
  return l

array_dtype_int8([5,200])

array([  5, -56], dtype=int8)

### np.int16

In [ ]:
def array_dtype_int16(lst):
  '''
  Create an array dtype int16
  return nD array
  '''
  l=np.array(lst,dtype=np.int16)
  return l
lst=[1,6000,70000]
array_dtype_int16(lst)

array([   1, 6000, 4464], dtype=int16)

### np.float

In [ ]:
def array_dtype_float(lst):
  '''
  Create an array dtype float
  return nD array
  '''
  l=np.array(lst,dtype=float)
  return l
lst=[1,3,5000,1000]
array_dtype_float(lst)

array([1.e+00, 3.e+00, 5.e+03, 1.e+03])

### np.bool

In [ ]:
def array_dtype_bool(lst):
  '''
  Create array dtype bool
  return nD array
  '''
  l=np.array(lst,dtype=np.bool8)
  return l
lst=[0,1,2]
array_dtype_bool(lst)

array([False,  True,  True])

# Creating Arrays

### np.arange

In [ ]:
def arange_1D_arr():
  '''
  Create any 1D array
  return array
  '''
  x=np.arange(1,9)
  return x
arange_1D_arr()

array([1, 2, 3, 4, 5, 6, 7, 8])

In [ ]:
def arrange_array(n):
  '''
  Create any array from 0 to n
  return array
  '''
  return np.arange(0,n+1)
arrange_array(8)

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

### np.linspace

In [ ]:
def linspace_arr(n):
  '''
  Create an array of the range 0 and n divided by 10
  return array
  '''
  return np.linspace(0,10)
linspace_arr(9)

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

### np.zeros

In [ ]:
def array_zeros_nxm(n,m):
  '''
  Create an nxm array of zeros
  return array
  '''
  return np.zeros((n,m))
array_zeros_nxm(4,9)

array([[0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [ ]:
def array_zeros_3D():
  '''
  Create any an 3D array of zeros
  return 3D array
  ''' 
  return np.zeros(3)
array_zeros_3D()

array([0., 0., 0.])

### np.ones

In [ ]:
def array_zeros_nxm(n,m):
  '''
  Create an NxM array of ones
  return array
  '''
  return np.ones((n,m))
array_zeros_nxm(3,3)

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

### np.full

In [ ]:
def array_full_3D(n,m,k):
  '''
  Create any an 3D array of seven, shape = (n,m,k)
  return 3D array
  ''' 
  return np.full((n,m),k)
array_full_3D(3,3,2)

array([[2, 2, 2],
       [2, 2, 2],
       [2, 2, 2]])