<a href="https://colab.research.google.com/github/Bahrombekk/numpy/blob/main/Qo'llanma.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

                                                              Numpy ga kirish
NumPy Pythonda ilmiy hisoblashlar uchun asosiy paketdir. Bu Python kutubxonasi boʻlib, u koʻp oʻlchovli massiv obyekti, turli hosila obʼyektlari (masalan, niqoblangan massivlar va matritsalar) hamda massivlar ustida tezkor operatsiyalar, jumladan, matematik, mantiqiy, shakllarni manipulyatsiya qilish, saralash, tanlash, kiritish/chiqarish uchun tartiblar assortimentini taqdim etadi. , diskret Furye o'zgarishlari, asosiy chiziqli algebra, asosiy statistik operatsiyalar, tasodifiy simulyatsiya va boshqalar.

numpy(object,dtype=None)
object--Type--array_like

bu list

In [1]:
ls=[1,2,3,4,5]
ls

[1, 2, 3, 4, 5]

bu ham list

In [3]:
l1=[[1,2,3],[3,4,5]]
l1

[[1, 2, 3], [3, 4, 5]]

bu ham list

In [4]:
l2=[[1,2,3],
    [3,4,5]]
l2

[[1, 2, 3], [3, 4, 5]]

buyam list ning bir ko'rinishi

In [6]:
l3=[[1,2,3],
    [2,3,4],
    [3,4,5]]
l3

[[1, 2, 3], [2, 3, 4], [3, 4, 5]]

In [26]:
print(type(l3))

<class 'list'>


In [7]:
l4=[[[1,2,3]],
    [[2,3,4]],
    [3,4,5]]
l4

[[[1, 2, 3]], [[2, 3, 4]], [3, 4, 5]]

                                            Bu numpy kutub xonasini import qilib olayabmiz

In [5]:
import numpy as np

bu array

In [9]:
a=np.array(ls)
a

array([1, 2, 3, 4, 5])

In [10]:
b=np.array(l1)
l1

[[1, 2, 3], [3, 4, 5]]

In [12]:
c=np.array(l2)
c

array([[1, 2, 3],
       [3, 4, 5]])

In [15]:
d=np.array(l3)
d

array([[1, 2, 3],
       [2, 3, 4],
       [3, 4, 5]])

endi arrayda xar xil tipdagi malumot kiritamiz

Masalan: int bilan str kelsa string o'tkazadi chunki string ustun

In [18]:
arr=np.array([1,2,'r',4])
arr

array(['1', '2', 'r', '4'], dtype='<U21')

int bilan float korsak arrayni str ga aylantirib yuboradi

In [20]:
arr=np.array([1,2,4.5,5])
arr

array([1. , 2. , 4.5, 5. ])

dtype--bu orqali biz arrayni taypini belgilasak bo'ladi.

Masalan: intni flotga,floatni intga,
intni va floatni str ga o'tkazzak bo'ladi,
strini ichida int tipiga tegishli son bo'lsa intgayam flotgayam o'tkazsa bo'ladi agar float bo'sa o'tkaza olmaydi

In [21]:
arr=np.array([1,2,3,'4',5],dtype=int)
arr

array([1, 2, 3, 4, 5])

In [22]:
arr=np.array([1,2,3,'r',5],dtype=int)
arr

ValueError: ignored

In [23]:
arr=np.array([1,2,3,'4.5',5],dtype=int)

ValueError: ignored

In [25]:
arr=np.array([1,2,3,4.5,5],dtype=int)
arr

array([1, 2, 3, 4, 5])

In [27]:
print(arr.dtype)

int64


In [28]:
print(type(arr))

<class 'numpy.ndarray'>


numpy.bool  --  Tru va Fols qabul qiladi

numpy.int8  --  (-128,127) ga cha son oladi.

numpy.uint  --  (0,255) gacha

numpy.float --  float oladi chunki u cheklanmagan butun bo'lib cheksiz ketadi

In [30]:
arr=np.array([1,2,3])
print(arr.dtype)

int64


In [31]:
arr=np.array([1,2,3],dtype=np.int8)
print(arr.dtype)

int8


In [33]:
arr=np.array([1,2,130,210,-130],dtype=np.int8)
print(arr.dtype)
arr

int8


array([   1,    2, -126,  -46,  126], dtype=int8)